version: '3'

services:
  database:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - docker-database.env

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - docker-wordpress.env
    volumes:
      - .:/var/www/html/wp-content/themes/tainacan

volumes:
  db_data: